DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS claims;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE claims (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  roles TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
